package es.sergiomartinez.imagechooser;

import javax.swing.ImageIcon;

public class Vista extends javax.swing.JFrame {

    StringBuffer choices;

    public Vista() {
        initComponents();
        choices = new StringBuffer("C--");
        jLImage.setText("");
        fondo();
    }

    private void cambiarChoices(int index, char c) {
        choices.setCharAt(index, c);
        fondo();
    }

    private void fondo() {
        String ruta = "src/main/java/images/" + choices + ".png";
        //d:usuarios\DAM2\Documents\NetBeansProjects\exccli\src\main\java\images
        ImageIcon icon = new ImageIcon(ruta);
        jLImage.setIcon(icon);
        //System.out.println(ruta);
        if (icon == null) {
            jLImage.setText("error");
        } else {
            jLImage.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCBUwu = new javax.swing.JCheckBox();
        jCBNaranja = new javax.swing.JCheckBox();
        jRBGato = new javax.swing.JRadioButton();
        jRBPerro = new javax.swing.JRadioButton();
        jLImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCBUwu.setText("UwU");
        jCBUwu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBUwuActionPerformed(evt);
            }
        });

        jCBNaranja.setText("NARANJA");
        jCBNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNaranjaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBGato);
        jRBGato.setSelected(true);
        jRBGato.setText("GATO");
        jRBGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBGatoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBPerro);
        jRBPerro.setText("PERRO");
        jRBPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPerroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBGato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBPerro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBUwu)
                        .addGap(18, 18, 18)
                        .addComponent(jCBNaranja)))
                .addGap(18, 18, 18)
                .addComponent(jLImage, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBGato)
                    .addComponent(jRBPerro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUwu)
                    .addComponent(jCBNaranja))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jLImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBUwuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBUwuActionPerformed
        // TODO add your handling code here:
        char c = '-';
        if (jCBUwu.isSelected()) {
            c = 'u';
        }

        cambiarChoices(2, c);
    }//GEN-LAST:event_jCBUwuActionPerformed

    private void jRBPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPerroActionPerformed
        // TODO add your handling code here:
        cambiarChoices(0, 'D');
    }//GEN-LAST:event_jRBPerroActionPerformed

    private void jRBGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBGatoActionPerformed
        // TODO add your handling code here:
        cambiarChoices(0, 'C');
    }//GEN-LAST:event_jRBGatoActionPerformed

    private void jCBNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNaranjaActionPerformed
        // TODO add your handling code here:
        char c = '-';
        if (jCBNaranja.isSelected()) {
            c = 'o';
        }

        cambiarChoices(1, c);

    }//GEN-LAST:event_jCBNaranjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCBNaranja;
    private javax.swing.JCheckBox jCBUwu;
    private javax.swing.JLabel jLImage;
    private javax.swing.JRadioButton jRBGato;
    private javax.swing.JRadioButton jRBPerro;
    // End of variables declaration//GEN-END:variables

}
